### ISSUE TITLE
EventSource.Write reflection error in RichPayloadEventSourceTest for some payloads

### ISSUE THREAD

**Issue by 4creators** [4creators/insights#7]
### Details

```

Test Name:  RichPayloadEventSourceSessionPerformanceCounterTest
Test FullName:  Microsoft.ApplicationInsights.Extensibility.Implementation.RichPayloadEventSourceTest.RichPayloadEventSourceSessionPerformanceCounterTest
Test Source:    E:\src\ms\insights\src\insights.git\Test\CoreSDK.Test\Net46\Extensibility\Implementation\RichPayloadEventSourceTest.cs : line 146
Test Outcome:   Failed
Test Duration:  0:00:00.0036675

Result StackTrace:  
at Microsoft.ApplicationInsights.Extensibility.Implementation.RichPayloadEventSourceTest.DoTracking(EventKeywords keywords, ITelemetry item, Type dataType, Action`2 track)
   at Microsoft.ApplicationInsights.Extensibility.Implementation.RichPayloadEventSourceTest.RichPayloadEventSourceSessionPerformanceCounterTest()
Result Message: Assert.AreEqual failed. Expected:<86928b39-6f87-4296-ae2a-fea2e724a2f4>. Actual:<EventSourceException while processing event "PerformanceCounter": System.Reflection.TargetException:Non-static method requires a target.>.

```

```

Test Name:  RichPayloadEventSourceMetricSentTest
Test FullName:  Microsoft.ApplicationInsights.Extensibility.Implementation.RichPayloadEventSourceTest.RichPayloadEventSourceMetricSentTest
Test Source:    E:\src\ms\insights\src\insights.git\Test\CoreSDK.Test\Net46\Extensibility\Implementation\RichPayloadEventSourceTest.cs : line 94
Test Outcome:   Failed
Test Duration:  0:00:00.0017349

Result StackTrace:  
at Microsoft.ApplicationInsights.Extensibility.Implementation.RichPayloadEventSourceTest.DoTracking(EventKeywords keywords, ITelemetry item, Type dataType, Action`2 track)
   at Microsoft.ApplicationInsights.Extensibility.Implementation.RichPayloadEventSourceTest.RichPayloadEventSourceMetricSentTest()
Result Message: Assert.AreEqual failed. Expected:<4fe3b95c-7ed2-4a82-a451-c26ba18f91a1>. Actual:<EventSourceException while processing event "Metric": System.Reflection.TargetException:Non-static method requires a target.>.

```

```

Test Name:  RichPayloadEventSourceExceptionSentTest
Test FullName:  Microsoft.ApplicationInsights.Extensibility.Implementation.RichPayloadEventSourceTest.RichPayloadEventSourceExceptionSentTest
Test Source:    E:\src\ms\insights\src\insights.git\Test\CoreSDK.Test\Net46\Extensibility\Implementation\RichPayloadEventSourceTest.cs : line 72
Test Outcome:   Failed
Test Duration:  0:00:00.1021756

Result StackTrace:  
at Microsoft.ApplicationInsights.Extensibility.Implementation.RichPayloadEventSourceTest.DoTracking(EventKeywords keywords, ITelemetry item, Type dataType, Action`2 track)
   at Microsoft.ApplicationInsights.Extensibility.Implementation.RichPayloadEventSourceTest.RichPayloadEventSourceExceptionSentTest()
Result Message: Assert.AreEqual failed. Expected:<a72def84-16b1-4aa7-8733-6122bebd8b9a>. Actual:<EventSourceException while processing event "Exception": System.Reflection.TargetException:Non-static method requires a target.>.

```

```

Test Name:  RichPayloadEventSourceDependencySentTest
Test FullName:  Microsoft.ApplicationInsights.Extensibility.Implementation.RichPayloadEventSourceTest.RichPayloadEventSourceDependencySentTest
Test Source:    E:\src\ms\insights\src\insights.git\Test\CoreSDK.Test\Net46\Extensibility\Implementation\RichPayloadEventSourceTest.cs : line 107
Test Outcome:   Failed
Test Duration:  0:00:00.0011003

Result StackTrace:  
at Microsoft.ApplicationInsights.Extensibility.Implementation.RichPayloadEventSourceTest.DoTracking(EventKeywords keywords, ITelemetry item, Type dataType, Action`2 track)
   at Microsoft.ApplicationInsights.Extensibility.Implementation.RichPayloadEventSourceTest.RichPayloadEventSourceDependencySentTest()
Result Message: Assert.AreEqual failed. Expected:<0d92084a-5266-48c5-b0be-206153a6d5ec>. Actual:<EventSourceException while processing event "RemoteDependency": System.Reflection.TargetException:Non-static method requires a target.>.

```
### Exception is converted to payload during serialization

Below stack trace of System.Reflection.TargetException

```

   at System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at System.Diagnostics.Tracing.PropertyValue.<>c__DisplayClass33_0.<GetBoxedValueTypePropertyGetter>b__0(PropertyValue container)
   at System.Diagnostics.Tracing.NullableTypeInfo.WriteData(TraceLoggingDataCollector collector, PropertyValue value)
   at System.Diagnostics.Tracing.InvokeTypeInfo.WriteData(TraceLoggingDataCollector collector, PropertyValue value)
   at System.Diagnostics.Tracing.InvokeTypeInfo.WriteData(TraceLoggingDataCollector collector, PropertyValue value)
   at System.Diagnostics.Tracing.EventSource.WriteImpl(String eventName, EventSourceOptions& options, Object data, Guid* pActivityId, Guid* pRelatedActivityId, TraceLoggingEventTypes eventTypes)

```

**Comment by 4creators** [comment]
Issue was caused both by missing EventData attribute on one of payloads and presence of nullable basic types i.e. int?, double? etc. in some payloads. While .NET Framework handles serialization of such data while writing to ETW listener flawlessly .NET Core throws System.Reflection.TargetException for any nullable type. This behaviour is in line with docs as both MSDN and blogs state that rich payload supports primitive types but there is no mention of nullable types with underlying primitive types.

Introduced changes may impact AI server and AI client communication so it will be further tested. Unfortunately currently we have no access to on premises or VSO instance of the server.

Fixed by commits:
- 690ea10d888a117242268aad247d45c5f71e4c0d
- cd6f1af4f3c4e75d02cfb196c2a4fd4055fed2ff
- df9f6314a21b7312f8f34c8519dbe6a4b5e694a2
- df9f6314a21b7312f8f34c8519dbe6a4b5e694a2
- fafc4040cab2ff8097cc7b10c57ed477acc6f38c
- 5f9d4efac7d7aa753c65942651a1f7434a25fc8a
- 3cd8e2cd5bf3731050e16184343b8c45be5a1b9a

[EventSource Rich Event Payload Support](https://msdnshared.blob.core.windows.net/media/MSDNBlogsFS/prod.evol.blogs.msdn.com/CommunityServer.Components.PostAttachments/00/10/64/26/84/EventSourceRichPayloads.docx) document excludes implicitly nullable types:

```

#### 1. NET V4.5 EventSource Payloads 

When EventSource was introduced in the V4.5 version of the .NET Runtime, it supported 
the following payloads:

    1)  Primitive types (bool, byte, short, char, int, long, float, double)
    2)  string, DateTime, Guid

This is sufficient for a broad range of event payloads.   However from time to time it is useful to log
more complex data that contains arrays or sub-records.  (or more typically arrays of sub-records). 
 In the .NET V4.6 library (or Version 1.1 of the EventSource Nuget Package), EventSource supports rich
data payloads that include arrays and records.  

#### 2. Rich EventSource Payloads 

Since Version 4.6, the rules have changed as follows

A valid EventSource payload type T is 

1)  A type permitted in .NET V4.5 
    a.   Primitive types (bool, byte, short, char, int, long, float, double)
    b.  string, DateTime, Guid
2)  An IEnumerable<T1> where T1 is an EventSource payload type. 
3)  A class that is either
    a.  Is decorated with the System.Diagnostics.Tracing.EventDataAttribute
    b.  Is decorated with the System.Runtime.CompilerServices.CompilerGeneratedAttribute
In addition all public properties on the class are EventSource payloads types.  
4)  Is the System.Collections.Generic.KeyValuePair<string,T1>  where T1 is a EventSource payload type

These rules have the following implications
1)  Since Arrays are IEnumerable, rule (2) implies arrays are valid
2)  Since anonymous types (e.g.  new { field1=3, field2=”hi” }, are decorated by the compiler with the
 CompilerGeneratedAttribute attribute, rule (3b) imply that anonymous types are also valid EventSource 
payloads if their fields are.  
3)  Since Dictionaries (or IDictionary)  with a string key are IEnumerable<KeyValuePair<string, T>>
 rule (2) and (4) imply that Dictionary<string T>  is a valid EventSource payload type if T is.    

The simple way of internalizing this is that EventSource support a form of ‘typed JSON’.  This capability
 makes it roughly as expressive as both JSON and XML.

```

Discussion of the subject can be found in Vance Morrison's [Rich Payload Data in EventSource V4.6.](https://blogs.msdn.microsoft.com/vancem/2015/09/20/rich-payload-data-in-eventsource-v4-6/) blog entry.
